### ISSUE TITLE
githubの変更と同時にlollipopを更新

### ISSUE THREAD

**Issue by jsuzukihawaii** [kanako-suzuki/smart-id-site#11]
githubの変更と同時にlollipopのFTPを更新してください

**Comment by kanako-suzuki** [comment]
更新

**Comment by nuts3745** [comment]
GitHub Actionsを利用すると自動化できます。

参考ブログ: [GitHub Actionsで「ロリポップ！」「ヘテムル」をもっと便利に使おう](https://tech.pepabo.com/2020/03/11/github-actions-for-lolipop-and-heteml/)
