### ISSUE TITLE
特許出願

### ISSUE THREAD

**Issue by jsuzukihawaii** [kanako-suzuki/smart-id-site#12]
Smart ID デジタル名刺は、スマートフォンで簡単に名刺生成が可能なプラットフォームです。
強固なセキュリティであるブロックチェーン技術を活用し、信頼性のある無限の繋がりを構築する為、ビジネス拡大を加速させます。
の下に

特許登録済　第6850463号（電子名刺発行管理）

を加える

**Comment by kanako-suzuki** [comment]
特許入力済み
